plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "D:\\Sportmultimedia Dropbox\\Diogo Caldas\\python\\medpal\\landing\\dist"
publishOrigin = "config"
commandOrigin = "config"
base = "D:\\Sportmultimedia Dropbox\\Diogo Caldas\\python\\medpal\\landing"
command = "npm install && npm run build"

[build.environment]
NODE_VERSION = "22"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]